kname: CI for Node.js

on:
  push:
    branches:
      - frontend   # This triggers the workflow when you push to the main branch
  pull_request:
    branches:
      - main   # This triggers the workflow when a PR is opened against the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
